version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
